sonar.projectKey=devops-java-lab
sonar.projectName=DevOps Java Lab
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
