apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-java-lab.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {app: {{ include "devops-java-lab.name" . }}}
  template:
    metadata:
      labels: {app: {{ include "devops-java-lab.name" . }}}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{containerPort: 8080}]
          readinessProbe: {httpGet: {path: /actuator/health/readiness, port: 8080}, initialDelaySeconds: 10}
          livenessProbe: {httpGet: {path: /actuator/health/liveness, port: 8080}, initialDelaySeconds: 20}
          resources: {{- toYaml .Values.resources | nindent 12 }}
