apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-java-lab.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector: {app: {{ include "devops-java-lab.name" . }}}
  ports: [{port: {{ .Values.service.port }}, targetPort: 8080}]
