replicaCount: 2
image:
  repository: ghcr.io/YOUR_GITHUB_USER/devops-java-lab
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  requests: {cpu: 100m, memory: 256Mi}
  limits: {cpu: 500m, memory: 512Mi}
